/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDevRouteImport } from './routes/_authenticated.dev'
import { Route as AuthenticatedMgrRouteImport } from './routes/_authenticated.mgr'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated.admin.access'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated.admin.config'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminGovernanceRouteImport } from './routes/_authenticated.admin.governance'
import { Route as AuthenticatedAdminIngestionRouteImport } from './routes/_authenticated.admin.ingestion'
import { Route as AuthenticatedAdminProjectSetupRouteImport } from './routes/_authenticated.admin.project-setup'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated.admin.projects'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedDevAskRouteImport } from './routes/_authenticated.dev.ask'
import { Route as AuthenticatedDevCoverageRouteImport } from './routes/_authenticated.dev.coverage'
import { Route as AuthenticatedDevEpicsRouteImport } from './routes/_authenticated.dev.epics'
import { Route as AuthenticatedDevScratchpadRouteImport } from './routes/_authenticated.dev.scratchpad'
import { Route as AuthenticatedDevWorkRouteImport } from './routes/_authenticated.dev.work'
import { Route as AuthenticatedMgrDashboardRouteImport } from './routes/_authenticated.mgr.dashboard'
import { Route as AuthenticatedMgrEpicsRouteImport } from './routes/_authenticated.mgr.epics'
import { Route as AuthenticatedMgrHandoverKitRouteImport } from './routes/_authenticated.mgr.handover-kit'
import { Route as AuthenticatedMgrOnboardingKitRouteImport } from './routes/_authenticated.mgr.onboarding-kit'
import { Route as AuthenticatedMgrScopeRouteImport } from './routes/_authenticated.mgr.scope'
import { Route as AuthenticatedMgrTeamRouteImport } from './routes/_authenticated.mgr.team'
import { Route as AuthenticatedAdminProjectsNewRouteImport } from './routes/_authenticated.admin.projects.new'
import { Route as AuthenticatedMgrTeamIndexRouteImport } from './routes/_authenticated.mgr.team.index'
import { Route as AuthenticatedMgrTeamIdRouteImport } from './routes/_authenticated.mgr.team.$id'
import { Route as AuthenticatedMgrTeamIdHandoverKitRouteImport } from './routes/_authenticated.mgr.team.$id.handover-kit'
import { Route as AuthenticatedMgrTeamIdOnboardingKitRouteImport } from './routes/_authenticated.mgr.team.$id.onboarding-kit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevRoute = AuthenticatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMgrRoute = AuthenticatedMgrRouteImport.update({
  id: '/mgr',
  path: '/mgr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGovernanceRoute =
  AuthenticatedAdminGovernanceRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIngestionRoute =
  AuthenticatedAdminIngestionRouteImport.update({
    id: '/ingestion',
    path: '/ingestion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectSetupRoute =
  AuthenticatedAdminProjectSetupRouteImport.update({
    id: '/project-setup',
    path: '/project-setup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDevAskRoute = AuthenticatedDevAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedDevRoute,
} as any)
const AuthenticatedDevCoverageRoute =
  AuthenticatedDevCoverageRouteImport.update({
    id: '/coverage',
    path: '/coverage',
    getParentRoute: () => AuthenticatedDevRoute,
  } as any)
const AuthenticatedDevEpicsRoute = AuthenticatedDevEpicsRouteImport.update({
  id: '/epics',
  path: '/epics',
  getParentRoute: () => AuthenticatedDevRoute,
} as any)
const AuthenticatedDevScratchpadRoute =
  AuthenticatedDevScratchpadRouteImport.update({
    id: '/scratchpad',
    path: '/scratchpad',
    getParentRoute: () => AuthenticatedDevRoute,
  } as any)
const AuthenticatedDevWorkRoute = AuthenticatedDevWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedDevRoute,
} as any)
const AuthenticatedMgrDashboardRoute =
  AuthenticatedMgrDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedMgrRoute,
  } as any)
const AuthenticatedMgrEpicsRoute = AuthenticatedMgrEpicsRouteImport.update({
  id: '/epics',
  path: '/epics',
  getParentRoute: () => AuthenticatedMgrRoute,
} as any)
const AuthenticatedMgrHandoverKitRoute =
  AuthenticatedMgrHandoverKitRouteImport.update({
    id: '/handover-kit',
    path: '/handover-kit',
    getParentRoute: () => AuthenticatedMgrRoute,
  } as any)
const AuthenticatedMgrOnboardingKitRoute =
  AuthenticatedMgrOnboardingKitRouteImport.update({
    id: '/onboarding-kit',
    path: '/onboarding-kit',
    getParentRoute: () => AuthenticatedMgrRoute,
  } as any)
const AuthenticatedMgrScopeRoute = AuthenticatedMgrScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => AuthenticatedMgrRoute,
} as any)
const AuthenticatedMgrTeamRoute = AuthenticatedMgrTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedMgrRoute,
} as any)
const AuthenticatedAdminProjectsNewRoute =
  AuthenticatedAdminProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProjectsRoute,
  } as any)
const AuthenticatedMgrTeamIndexRoute =
  AuthenticatedMgrTeamIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMgrTeamRoute,
  } as any)
const AuthenticatedMgrTeamIdRoute = AuthenticatedMgrTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMgrTeamRoute,
} as any)
const AuthenticatedMgrTeamIdHandoverKitRoute =
  AuthenticatedMgrTeamIdHandoverKitRouteImport.update({
    id: '/handover-kit',
    path: '/handover-kit',
    getParentRoute: () => AuthenticatedMgrTeamIdRoute,
  } as any)
const AuthenticatedMgrTeamIdOnboardingKitRoute =
  AuthenticatedMgrTeamIdOnboardingKitRouteImport.update({
    id: '/onboarding-kit',
    path: '/onboarding-kit',
    getParentRoute: () => AuthenticatedMgrTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dev': typeof AuthenticatedDevRouteWithChildren
  '/mgr': typeof AuthenticatedMgrRouteWithChildren
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/project-setup': typeof AuthenticatedAdminProjectSetupRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dev/ask': typeof AuthenticatedDevAskRoute
  '/dev/coverage': typeof AuthenticatedDevCoverageRoute
  '/dev/epics': typeof AuthenticatedDevEpicsRoute
  '/dev/scratchpad': typeof AuthenticatedDevScratchpadRoute
  '/dev/work': typeof AuthenticatedDevWorkRoute
  '/mgr/dashboard': typeof AuthenticatedMgrDashboardRoute
  '/mgr/epics': typeof AuthenticatedMgrEpicsRoute
  '/mgr/handover-kit': typeof AuthenticatedMgrHandoverKitRoute
  '/mgr/onboarding-kit': typeof AuthenticatedMgrOnboardingKitRoute
  '/mgr/scope': typeof AuthenticatedMgrScopeRoute
  '/mgr/team': typeof AuthenticatedMgrTeamRouteWithChildren
  '/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/mgr/team/$id': typeof AuthenticatedMgrTeamIdRouteWithChildren
  '/mgr/team/': typeof AuthenticatedMgrTeamIndexRoute
  '/mgr/team/$id/handover-kit': typeof AuthenticatedMgrTeamIdHandoverKitRoute
  '/mgr/team/$id/onboarding-kit': typeof AuthenticatedMgrTeamIdOnboardingKitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dev': typeof AuthenticatedDevRouteWithChildren
  '/mgr': typeof AuthenticatedMgrRouteWithChildren
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/project-setup': typeof AuthenticatedAdminProjectSetupRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dev/ask': typeof AuthenticatedDevAskRoute
  '/dev/coverage': typeof AuthenticatedDevCoverageRoute
  '/dev/epics': typeof AuthenticatedDevEpicsRoute
  '/dev/scratchpad': typeof AuthenticatedDevScratchpadRoute
  '/dev/work': typeof AuthenticatedDevWorkRoute
  '/mgr/dashboard': typeof AuthenticatedMgrDashboardRoute
  '/mgr/epics': typeof AuthenticatedMgrEpicsRoute
  '/mgr/handover-kit': typeof AuthenticatedMgrHandoverKitRoute
  '/mgr/onboarding-kit': typeof AuthenticatedMgrOnboardingKitRoute
  '/mgr/scope': typeof AuthenticatedMgrScopeRoute
  '/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/mgr/team/$id': typeof AuthenticatedMgrTeamIdRouteWithChildren
  '/mgr/team': typeof AuthenticatedMgrTeamIndexRoute
  '/mgr/team/$id/handover-kit': typeof AuthenticatedMgrTeamIdHandoverKitRoute
  '/mgr/team/$id/onboarding-kit': typeof AuthenticatedMgrTeamIdOnboardingKitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dev': typeof AuthenticatedDevRouteWithChildren
  '/_authenticated/mgr': typeof AuthenticatedMgrRouteWithChildren
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/config': typeof AuthenticatedAdminConfigRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/_authenticated/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/_authenticated/admin/project-setup': typeof AuthenticatedAdminProjectSetupRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dev/ask': typeof AuthenticatedDevAskRoute
  '/_authenticated/dev/coverage': typeof AuthenticatedDevCoverageRoute
  '/_authenticated/dev/epics': typeof AuthenticatedDevEpicsRoute
  '/_authenticated/dev/scratchpad': typeof AuthenticatedDevScratchpadRoute
  '/_authenticated/dev/work': typeof AuthenticatedDevWorkRoute
  '/_authenticated/mgr/dashboard': typeof AuthenticatedMgrDashboardRoute
  '/_authenticated/mgr/epics': typeof AuthenticatedMgrEpicsRoute
  '/_authenticated/mgr/handover-kit': typeof AuthenticatedMgrHandoverKitRoute
  '/_authenticated/mgr/onboarding-kit': typeof AuthenticatedMgrOnboardingKitRoute
  '/_authenticated/mgr/scope': typeof AuthenticatedMgrScopeRoute
  '/_authenticated/mgr/team': typeof AuthenticatedMgrTeamRouteWithChildren
  '/_authenticated/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/_authenticated/mgr/team/$id': typeof AuthenticatedMgrTeamIdRouteWithChildren
  '/_authenticated/mgr/team/': typeof AuthenticatedMgrTeamIndexRoute
  '/_authenticated/mgr/team/$id/handover-kit': typeof AuthenticatedMgrTeamIdHandoverKitRoute
  '/_authenticated/mgr/team/$id/onboarding-kit': typeof AuthenticatedMgrTeamIdOnboardingKitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dev'
    | '/mgr'
    | '/admin/access'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/governance'
    | '/admin/ingestion'
    | '/admin/project-setup'
    | '/admin/projects'
    | '/admin/users'
    | '/dev/ask'
    | '/dev/coverage'
    | '/dev/epics'
    | '/dev/scratchpad'
    | '/dev/work'
    | '/mgr/dashboard'
    | '/mgr/epics'
    | '/mgr/handover-kit'
    | '/mgr/onboarding-kit'
    | '/mgr/scope'
    | '/mgr/team'
    | '/admin/projects/new'
    | '/mgr/team/$id'
    | '/mgr/team/'
    | '/mgr/team/$id/handover-kit'
    | '/mgr/team/$id/onboarding-kit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dev'
    | '/mgr'
    | '/admin/access'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/governance'
    | '/admin/ingestion'
    | '/admin/project-setup'
    | '/admin/projects'
    | '/admin/users'
    | '/dev/ask'
    | '/dev/coverage'
    | '/dev/epics'
    | '/dev/scratchpad'
    | '/dev/work'
    | '/mgr/dashboard'
    | '/mgr/epics'
    | '/mgr/handover-kit'
    | '/mgr/onboarding-kit'
    | '/mgr/scope'
    | '/admin/projects/new'
    | '/mgr/team/$id'
    | '/mgr/team'
    | '/mgr/team/$id/handover-kit'
    | '/mgr/team/$id/onboarding-kit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dev'
    | '/_authenticated/mgr'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/config'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/governance'
    | '/_authenticated/admin/ingestion'
    | '/_authenticated/admin/project-setup'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/users'
    | '/_authenticated/dev/ask'
    | '/_authenticated/dev/coverage'
    | '/_authenticated/dev/epics'
    | '/_authenticated/dev/scratchpad'
    | '/_authenticated/dev/work'
    | '/_authenticated/mgr/dashboard'
    | '/_authenticated/mgr/epics'
    | '/_authenticated/mgr/handover-kit'
    | '/_authenticated/mgr/onboarding-kit'
    | '/_authenticated/mgr/scope'
    | '/_authenticated/mgr/team'
    | '/_authenticated/admin/projects/new'
    | '/_authenticated/mgr/team/$id'
    | '/_authenticated/mgr/team/'
    | '/_authenticated/mgr/team/$id/handover-kit'
    | '/_authenticated/mgr/team/$id/onboarding-kit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mgr': {
      id: '/_authenticated/mgr'
      path: '/mgr'
      fullPath: '/mgr'
      preLoaderRoute: typeof AuthenticatedMgrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config': {
      id: '/_authenticated/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/governance': {
      id: '/_authenticated/admin/governance'
      path: '/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AuthenticatedAdminGovernanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ingestion': {
      id: '/_authenticated/admin/ingestion'
      path: '/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AuthenticatedAdminIngestionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/project-setup': {
      id: '/_authenticated/admin/project-setup'
      path: '/project-setup'
      fullPath: '/admin/project-setup'
      preLoaderRoute: typeof AuthenticatedAdminProjectSetupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dev/ask': {
      id: '/_authenticated/dev/ask'
      path: '/ask'
      fullPath: '/dev/ask'
      preLoaderRoute: typeof AuthenticatedDevAskRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/_authenticated/dev/coverage': {
      id: '/_authenticated/dev/coverage'
      path: '/coverage'
      fullPath: '/dev/coverage'
      preLoaderRoute: typeof AuthenticatedDevCoverageRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/_authenticated/dev/epics': {
      id: '/_authenticated/dev/epics'
      path: '/epics'
      fullPath: '/dev/epics'
      preLoaderRoute: typeof AuthenticatedDevEpicsRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/_authenticated/dev/scratchpad': {
      id: '/_authenticated/dev/scratchpad'
      path: '/scratchpad'
      fullPath: '/dev/scratchpad'
      preLoaderRoute: typeof AuthenticatedDevScratchpadRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/_authenticated/dev/work': {
      id: '/_authenticated/dev/work'
      path: '/work'
      fullPath: '/dev/work'
      preLoaderRoute: typeof AuthenticatedDevWorkRouteImport
      parentRoute: typeof AuthenticatedDevRoute
    }
    '/_authenticated/mgr/dashboard': {
      id: '/_authenticated/mgr/dashboard'
      path: '/dashboard'
      fullPath: '/mgr/dashboard'
      preLoaderRoute: typeof AuthenticatedMgrDashboardRouteImport
      parentRoute: typeof AuthenticatedMgrRoute
    }
    '/_authenticated/mgr/epics': {
      id: '/_authenticated/mgr/epics'
      path: '/epics'
      fullPath: '/mgr/epics'
      preLoaderRoute: typeof AuthenticatedMgrEpicsRouteImport
      parentRoute: typeof AuthenticatedMgrRoute
    }
    '/_authenticated/mgr/handover-kit': {
      id: '/_authenticated/mgr/handover-kit'
      path: '/handover-kit'
      fullPath: '/mgr/handover-kit'
      preLoaderRoute: typeof AuthenticatedMgrHandoverKitRouteImport
      parentRoute: typeof AuthenticatedMgrRoute
    }
    '/_authenticated/mgr/onboarding-kit': {
      id: '/_authenticated/mgr/onboarding-kit'
      path: '/onboarding-kit'
      fullPath: '/mgr/onboarding-kit'
      preLoaderRoute: typeof AuthenticatedMgrOnboardingKitRouteImport
      parentRoute: typeof AuthenticatedMgrRoute
    }
    '/_authenticated/mgr/scope': {
      id: '/_authenticated/mgr/scope'
      path: '/scope'
      fullPath: '/mgr/scope'
      preLoaderRoute: typeof AuthenticatedMgrScopeRouteImport
      parentRoute: typeof AuthenticatedMgrRoute
    }
    '/_authenticated/mgr/team': {
      id: '/_authenticated/mgr/team'
      path: '/team'
      fullPath: '/mgr/team'
      preLoaderRoute: typeof AuthenticatedMgrTeamRouteImport
      parentRoute: typeof AuthenticatedMgrRoute
    }
    '/_authenticated/admin/projects/new': {
      id: '/_authenticated/admin/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AuthenticatedAdminProjectsNewRouteImport
      parentRoute: typeof AuthenticatedAdminProjectsRoute
    }
    '/_authenticated/mgr/team/': {
      id: '/_authenticated/mgr/team/'
      path: '/'
      fullPath: '/mgr/team/'
      preLoaderRoute: typeof AuthenticatedMgrTeamIndexRouteImport
      parentRoute: typeof AuthenticatedMgrTeamRoute
    }
    '/_authenticated/mgr/team/$id': {
      id: '/_authenticated/mgr/team/$id'
      path: '/$id'
      fullPath: '/mgr/team/$id'
      preLoaderRoute: typeof AuthenticatedMgrTeamIdRouteImport
      parentRoute: typeof AuthenticatedMgrTeamRoute
    }
    '/_authenticated/mgr/team/$id/handover-kit': {
      id: '/_authenticated/mgr/team/$id/handover-kit'
      path: '/handover-kit'
      fullPath: '/mgr/team/$id/handover-kit'
      preLoaderRoute: typeof AuthenticatedMgrTeamIdHandoverKitRouteImport
      parentRoute: typeof AuthenticatedMgrTeamIdRoute
    }
    '/_authenticated/mgr/team/$id/onboarding-kit': {
      id: '/_authenticated/mgr/team/$id/onboarding-kit'
      path: '/onboarding-kit'
      fullPath: '/mgr/team/$id/onboarding-kit'
      preLoaderRoute: typeof AuthenticatedMgrTeamIdOnboardingKitRouteImport
      parentRoute: typeof AuthenticatedMgrTeamIdRoute
    }
  }
}

interface AuthenticatedAdminProjectsRouteChildren {
  AuthenticatedAdminProjectsNewRoute: typeof AuthenticatedAdminProjectsNewRoute
}

const AuthenticatedAdminProjectsRouteChildren: AuthenticatedAdminProjectsRouteChildren =
  {
    AuthenticatedAdminProjectsNewRoute: AuthenticatedAdminProjectsNewRoute,
  }

const AuthenticatedAdminProjectsRouteWithChildren =
  AuthenticatedAdminProjectsRoute._addFileChildren(
    AuthenticatedAdminProjectsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminGovernanceRoute: typeof AuthenticatedAdminGovernanceRoute
  AuthenticatedAdminIngestionRoute: typeof AuthenticatedAdminIngestionRoute
  AuthenticatedAdminProjectSetupRoute: typeof AuthenticatedAdminProjectSetupRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminGovernanceRoute: AuthenticatedAdminGovernanceRoute,
  AuthenticatedAdminIngestionRoute: AuthenticatedAdminIngestionRoute,
  AuthenticatedAdminProjectSetupRoute: AuthenticatedAdminProjectSetupRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDevRouteChildren {
  AuthenticatedDevAskRoute: typeof AuthenticatedDevAskRoute
  AuthenticatedDevCoverageRoute: typeof AuthenticatedDevCoverageRoute
  AuthenticatedDevEpicsRoute: typeof AuthenticatedDevEpicsRoute
  AuthenticatedDevScratchpadRoute: typeof AuthenticatedDevScratchpadRoute
  AuthenticatedDevWorkRoute: typeof AuthenticatedDevWorkRoute
}

const AuthenticatedDevRouteChildren: AuthenticatedDevRouteChildren = {
  AuthenticatedDevAskRoute: AuthenticatedDevAskRoute,
  AuthenticatedDevCoverageRoute: AuthenticatedDevCoverageRoute,
  AuthenticatedDevEpicsRoute: AuthenticatedDevEpicsRoute,
  AuthenticatedDevScratchpadRoute: AuthenticatedDevScratchpadRoute,
  AuthenticatedDevWorkRoute: AuthenticatedDevWorkRoute,
}

const AuthenticatedDevRouteWithChildren =
  AuthenticatedDevRoute._addFileChildren(AuthenticatedDevRouteChildren)

interface AuthenticatedMgrTeamIdRouteChildren {
  AuthenticatedMgrTeamIdHandoverKitRoute: typeof AuthenticatedMgrTeamIdHandoverKitRoute
  AuthenticatedMgrTeamIdOnboardingKitRoute: typeof AuthenticatedMgrTeamIdOnboardingKitRoute
}

const AuthenticatedMgrTeamIdRouteChildren: AuthenticatedMgrTeamIdRouteChildren =
  {
    AuthenticatedMgrTeamIdHandoverKitRoute:
      AuthenticatedMgrTeamIdHandoverKitRoute,
    AuthenticatedMgrTeamIdOnboardingKitRoute:
      AuthenticatedMgrTeamIdOnboardingKitRoute,
  }

const AuthenticatedMgrTeamIdRouteWithChildren =
  AuthenticatedMgrTeamIdRoute._addFileChildren(
    AuthenticatedMgrTeamIdRouteChildren,
  )

interface AuthenticatedMgrTeamRouteChildren {
  AuthenticatedMgrTeamIdRoute: typeof AuthenticatedMgrTeamIdRouteWithChildren
  AuthenticatedMgrTeamIndexRoute: typeof AuthenticatedMgrTeamIndexRoute
}

const AuthenticatedMgrTeamRouteChildren: AuthenticatedMgrTeamRouteChildren = {
  AuthenticatedMgrTeamIdRoute: AuthenticatedMgrTeamIdRouteWithChildren,
  AuthenticatedMgrTeamIndexRoute: AuthenticatedMgrTeamIndexRoute,
}

const AuthenticatedMgrTeamRouteWithChildren =
  AuthenticatedMgrTeamRoute._addFileChildren(AuthenticatedMgrTeamRouteChildren)

interface AuthenticatedMgrRouteChildren {
  AuthenticatedMgrDashboardRoute: typeof AuthenticatedMgrDashboardRoute
  AuthenticatedMgrEpicsRoute: typeof AuthenticatedMgrEpicsRoute
  AuthenticatedMgrHandoverKitRoute: typeof AuthenticatedMgrHandoverKitRoute
  AuthenticatedMgrOnboardingKitRoute: typeof AuthenticatedMgrOnboardingKitRoute
  AuthenticatedMgrScopeRoute: typeof AuthenticatedMgrScopeRoute
  AuthenticatedMgrTeamRoute: typeof AuthenticatedMgrTeamRouteWithChildren
}

const AuthenticatedMgrRouteChildren: AuthenticatedMgrRouteChildren = {
  AuthenticatedMgrDashboardRoute: AuthenticatedMgrDashboardRoute,
  AuthenticatedMgrEpicsRoute: AuthenticatedMgrEpicsRoute,
  AuthenticatedMgrHandoverKitRoute: AuthenticatedMgrHandoverKitRoute,
  AuthenticatedMgrOnboardingKitRoute: AuthenticatedMgrOnboardingKitRoute,
  AuthenticatedMgrScopeRoute: AuthenticatedMgrScopeRoute,
  AuthenticatedMgrTeamRoute: AuthenticatedMgrTeamRouteWithChildren,
}

const AuthenticatedMgrRouteWithChildren =
  AuthenticatedMgrRoute._addFileChildren(AuthenticatedMgrRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDevRoute: typeof AuthenticatedDevRouteWithChildren
  AuthenticatedMgrRoute: typeof AuthenticatedMgrRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDevRoute: AuthenticatedDevRouteWithChildren,
  AuthenticatedMgrRoute: AuthenticatedMgrRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
